# Generated by Django 4.0.6 on 2022-07-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('IdBus', models.AutoField(primary_key=True, serialize=False)),
                ('NumeroBus', models.CharField(max_length=10)),
                ('TotalAsientos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('IdChofer', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('IdBus', models.IntegerField()),
                ('IdTrayecto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('IdPasajero', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Asiento', models.CharField(max_length=5)),
                ('IdBus', models.IntegerField()),
                ('IdTrayecto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('IdTrayecto', models.AutoField(primary_key=True, serialize=False)),
                ('NombreTrayecto', models.CharField(max_length=200)),
                ('Horario', models.DateTimeField()),
            ],
        ),
    ]
