# Generated by Django 2.1.15 on 2022-07-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='Apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='Nombre',
            field=models.CharField(max_length=100),
        ),
    ]
