# Generated by Django 2.2 on 2022-07-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220716_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='NumeroBus',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='IdBus',
            field=models.IntegerField(unique=True),
        ),
    ]
