# Generated by Django 2.2 on 2022-07-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220717_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='Asiento',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
