# Generated by Django 2.2 on 2022-07-18 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220717_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='IdBus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Bus'),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='IdTrayecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Trayecto'),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='IdBus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Bus'),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='IdTrayecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Trayecto'),
        ),
    ]
