# Generated by Django 2.2 on 2022-07-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220718_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='TotalAsientos',
        ),
        migrations.AddField(
            model_name='bus',
            name='AsientoRestantes',
            field=models.IntegerField(default=0),
        ),
    ]
