# Generated by Django 2.2 on 2022-07-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220719_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='Capacidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='AsientoRestantes',
            field=models.IntegerField(),
        ),
    ]
